![LL%20&%20SU.jpg](attachment:LL%20&%20SU.jpg)

# Assignment \#1: Introduction to Python




This Assignments aims to test introductory Python skills, specifically content covered in the _Introduction to Python_ and _Intermediate Python_ DataCamp courses.

## Lists and sets

### Write dynamic code to solve the following questions:

Display the given Python list in reverse order.

In [18]:
a = [100, 200, 300, 400, 500]

a.reverse()
print(a)


[500, 400, 300, 200, 100]


Given a list, turn every item of the list into its square.

In [16]:
a = [1, 2, 3, 4, 5, 6, 7]

import numpy as np
arr = np.array(a)
print(arr ** 2)


[ 1  4  9 16 25 36 49]


Remove empty strings from the list of strings.

In [15]:
a = ["Mike", "", "Emma", "Kelly", "", "Brad"]

for item in a:
    if item == "":
        a.remove(item)
print(a)


['Mike', 'Emma', 'Kelly', 'Brad']


Given a Python list, find value 15 in the list, and if it is present, replace it with 150. Only update the first occurrence of a value.

In [14]:
a = [5, 10, 15, 20, 15, 50, 20]


a.insert(a.index(15),150)
print(a)


[5, 10, 150, 15, 20, 15, 50, 20]


Given a Python list, remove all occurrence of 15 from the list.

In [13]:
a = [5, 10, 15, 20, 15, 50, 20]
for item in a:
    if item == 15:
        a.remove(item)
print(a)

[5, 10, 20, 50, 20]


Add list of elements in *aList* to a given set, *aSet*.

In [22]:
aSet = {"Dog", "Bird", "Horse"}
aList = ["Lizard", "Cat", "Rabbit"]

aSet.update(aList)
print(aSet)


{'Cat', 'Dog', 'Rabbit', 'Bird', 'Horse', 'Lizard'}


Return a set of identical items from two Python sets.

In [23]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

print(set1.intersection(set2))


{40, 50, 30}


Given two Python sets, update first set with items that exist only in the first set and not in the second set.

In [25]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1.difference_update(set2)
print(set1)


{10, 20}


Remove items from *set1* that are not common to both *set1* and *set2*.

In [26]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

set1.intersection_update(set2)
print(set1)


{40, 50, 30}


Return a set of all elements in either *set1* or *set2*, but not both.

In [27]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

set1.symmetric_difference(set2)


{10, 20, 60, 70}

## Dictionaries
Create a dictionary with the following key-value pairs: apple = 10, orange = 12, banana = 16, grape = 4.

In [31]:
fruit = {'apple':10, 'orange':12, 'banana':16,'grape':4}


Use the dictionary to retrieve the number of apples.

In [32]:
fruit['apple']


10

Use the dictionary to display the total fruit.

In [33]:
sum(fruit.values())

42

Add the following record to the dictionary: 23 pears

In [37]:
fruit['pears'] = 23


Retrieve and display the most occuring fruit from dictionary.


In [43]:
max_num = 0
max_fruit = ''
for item in fruit:
    if fruit[item] > max_num:
        max_num = fruit[item]
        max_fruit = item
print('{} appear {} time(s)'.format(max_fruit, max_num))
        


pears appear 23 time(s)


Display fruit  in alphabetiacal order:



In [48]:
fruit_list = list(fruit.keys())
fruit_list.sort()
print(fruit_list)


['apple', 'banana', 'grape', 'orange', 'pears']


## Python Functions
Create a function named "sign()" that returns "positive", "negative" or "zero" given an integer as input.

In [50]:
#Insert function:
def sign(num):
    if num > 0:
        return 'postive'
    elif num < 0:
        return 'negative'
    else:
        return 'zero'
# Test
for x in [-1, 0, 1]:
  print(sign(x))

negative
zero
postive


Write a function named "my_min()" that returns the minimum value given arbitrary 
number of integers as input parameters.

In [52]:
# Insert function 
def my_min(*args):
    return(min(args))
# Test
print(my_min(4, 5, 6, 7, 2))
print(my_min(-10, 5, 3, -4, 1, 10, 3, 6))

2
-10


Write a recursive function to display the Fibonacci sequence using recursion. 

The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms i.e. the n-th term is the sum of (n-1)-th and (n-2)-th term.

In [53]:
def recur_fibo(n):
  # Insert code here
    if n<= 1:
        return n
    else:
        return(recur_fibo(n-1) + recur_fibo(n-2))

# Test
for i in range(10):
  print(recur_fibo(i))

0
1
1
2
3
5
8
13
21
34


## Python Classes
Create a constructor for class "Circle" that takes x and y coordinates (center of cirlce) and radius as arguments to initialize an instance of the class.

In [116]:
import math

# Insert class here:
class Circle:
  # Insert constructor code
    def __init__(self,x = 0,y = 0,r = 0):
        self.x = x
        self.y = y
        self.r = r

    def str_circle(self):
        print(f'Circle at location x = {self.x} and y = {self.y} with radius = {self.r}')

    def dist(self, other):
        # Insert code
        return math.sqrt((self.x-other.x) ** 2 + (self.y - other.y) ** 2)

    def overlap(self, other):
        # Insert code
        check = self.dist(other)
        if  check > (self.r + other.r) :
            return False
        else:
            return True

    def area(self):
        # Insert code
        return math.pi * self.r ** 2

    def overlap_area(self, other):
        # Insert code
        if self.overlap(other):
            d = self.dist(other)
            r1 = self.r 
            R = other.r
            return (r1 ** 2) * (math.acos((d ** 2 + r1 ** 2 - R ** 2) / (2*d*r1))) + R ** 2 * acos((d ** 2 + R ** 2 - r1 **2)/(2*d*R)) - 0.5 * math.sqrt((-d + r1 + R)*(d + r1 - R)*(d - r1 + R)*(d + r1 + R))
        else:
            print("Circles do not overlap")



Create the following two circles:
*   circle 1: x = 2, y = 1, rad = 1

*   circle 2: x = -1, y = -2, rad 3 


In [117]:
# Insert code
circle1 = Circle(x = 2, y = 1, r = 1)
circle2 = Circle(x = -1, y = -2, r = 3)

Complete the function "str_circle()" to print the properties of both circles as follow:

"Circle at location x = 2 and y = 3 with radius = 1"



In [118]:
circle1.str_circle()
circle2.str_circle()

Circle at location x = 2 and y = 1 with radius = 1
Circle at location x = -1 and y = -2 with radius = 3


Complete the function "dist()" to return the euclidean distance between two circles' centers. Print the distance between circle 1 and 2.

In [119]:
# Test

center_dist = circle1.dist(circle2)
print(center_dist)

4.242640687119285


Complete the function "overlap()". The function should return True if the circles overlap and False otherwise.

In [120]:
# Test
circle1.overlap(circle2)

False

Complete fuction "area()". The function should return the area of the circle.

In [121]:
# Test
circle1.area()

3.141592653589793

Complete function "overlap_area". The function should return the overlapping area between two circles. 

If the circles do not overlap, return the message: "Circles do not overlap"

The formula for calculating the overlapping area between two circles is provided below:

\begin{equation}
\small
A = 
r^2\text{cos}^{-1}(\frac{d^2+r^2-R^2}{2dr}) + R^2\text{cos}^{-1}(\frac{d^2+R^2-r^2}{2dR}) -
\frac{1}{2}\sqrt{(-d+r+R)(d+r-R)(d-r+R)(d+r+R)}
\end{equation}


$\;\;\;\;\;\;\;\;$A = area of overlapping <br>
$\;\;\;\;\;\;\;\;$r = radius of circle 1 <br>
$\;\;\;\;\;\;\;\;$R = radius of circle 2 <br>
$\;\;\;\;\;\;\;\;$d = distance between the circles <br>

In [122]:
# Test
circle1.overlap_area(circle2)

Circles do not overlap


##  Introduction to Numpy

In [ ]:
# Import numpy library
import numpy as np

Given the matrix, write code to compute the average over all the entries in the matrix.

In [123]:
A = [[ 1.27411064,  0.05188032, -1.27088046],
       [-0.78844599, -0.14775522, -0.28198009]]

a = np.array(A)

np.mean(a)


-0.1938451333333334

Given two vectors of data, print the Euclidean distance between them.

In [125]:

VEC1 = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]
VEC2 = [0.16257878, -0.88344182,  1.14405499,  0.33765161,  1.206262]

vec1 = np.array(VEC1)
vec2 = np.array(VEC2)

print(math.sqrt(np.sum((vec1-vec2) ** 2)))


2.27642738170527
2.27642738170527


Given two matrices of appropriate dimensions, print their matrix product.


In [128]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, 0.42421340135829255]]

B = [[0.6583596987271446, 1.0128241391924433],
        [0.37883705753739877, 0.42421340135829255]]

a = np.array(A)
b = np.array(B)

print(np.matmul(a,b))


[[0.81713281 1.09645617]
 [0.40946045 0.5626395 ]]


Given `start` and `end` integer values, create a 1-d array consisting of all integer values between `start` and `end` (inclusive).

In [130]:
start = 3
end = 10

a = np.array(list(range(start,end+1)))
a

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Given a vector of integer data, print all the entries that are even.


In [131]:
VEC = [-3, 5, 1, 2, 18, 2, 234, 11]

vec = np.array(VEC)
print(vec[vec % 2 == 0])
# Insert code


[  2  18   2 234]


Given two matrices, print whether they are equal (i.e. all their corresponding entries are the same).


In [139]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, 0.42421340135829255],
        [-0.6905233695318467, -0.498554227530507]]
B = [[0.6583596987271446, 1.0128241391924433],
        [0.37883705753739877, 0.42421340135829255],
        [-0.6905233695318467, -0.498554227530507]]
 
a = np.array(A)
b = np.array(B)

if (a == b).all():
    print('They are equal')
else:
    print('They are not equal')


They are not equal


Given two vectors of data, print the cosine distance between them.


In [142]:
VEC1 = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]
VEC2 = [ 0.16257878, -0.88344182,  1.14405499,  0.33765161,  1.206262]

vec1 = np.array(VEC1)
vec2 = np.array(VEC2)

print(np.dot(vec1,vec2)/(np.linalg.norm(vec1)*np.linalg.norm(vec2)))


-0.46279558166521795


Given a vector of data, scale (multiply) all the entries in the vector by the vector mean and print the result.

In [143]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

print(np.mean(vec)*vec)


[ 0.017301   -0.00432749  0.02962064 -0.0238656   0.00417945]


Given a matrix, subtract the column mean from each entry. This has the effect of zero-centering the data and is often done in algorithms such as principal components analysis or when running computer vision models.

In [144]:
A = [[0.6583596987271446, 1.0128241391924433],
       [0.37783705753739877, 0.42421340135829255],
       [-0.6905233695318467, -0.498554227530507]]

a = np.array(A)

a = a - np.mean(a,axis = 0)
a


array([[ 0.54313524,  0.69999637],
       [ 0.2626126 ,  0.11138563],
       [-0.80574783, -0.811382  ]])

Given a vector of data, compute the softmax scores of the vector.



In [145]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

np.exp(vec)/np.sum(np.exp(a))


array([0.10994028, 0.15133133, 0.09164567, 0.20197083, 0.13345871])

Given a matrix, print whether or not there are any NaN values in the matrix. 

In [149]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, float("nan")],
        [-0.6905233695318467, -0.498554227530507]]

a = np.array(A)
if (np.isnan(a)).any():
    print('There exist NaN values')
else:
    print('NaN values do not exist')


There exist NaN values


Given a vector of data, normalize the vector to have 0 mean and variance of 1. (Z-score normalization)]

In [ ]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

# Insert code
